const types = {
  LOADING: 'LOADING',
  LOADING_DONE: 'LOADING_DONE',
  ERROR: 'ERROR',

  // set params
  SET_PARAMS_USER_DETAIL: 'SET_PARAMS_USER_DETAIL',

  // get list users
  GET_LIST_USERS: 'GET_LIST_USERS',
  GET_LIST_USERS_SUCCESS: 'GET_LIST_USERS_SUCCESS',
  GET_LIST_USERS_FAILURE: 'GET_LIST_USERS_FAILURE',

  // get user by id
  GET_USER_BY_ID: 'GET_USER_BY_ID',
  GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAILURE: 'GET_USER_BY_ID_FAILURE'
};

export default types;
